msix_config:
  display_name: e-pos
  publisher_display_name: AndromedaSoftwareSolutions
  identity_name: com.andromedasoftware.epos
  msix_version: 1.0.0.0
#  publisher: CN=ViduraVijerathne, O=AndromedaSoftwareSolutions
#  sign_msix: false
  logo_path: assets/logo.ico
  capabilities: internetClient, localSystem