name: Build Windows Release

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: windows-latest  # Run the job on a Windows virtual machine
    steps:
      - uses: actions/checkout@v2  # Checkout your code from GitHub
      - uses: subosito/flutter-action@v1  # Setup Flutter environment
        with:
          channel: stable  # Use the stable Flutter channel
      - run: flutter pub get  # Install dependencies
      - run: flutter build windows --release  # Build the Windows release
      - uses: TheDoctor0/zip-release@0.7.6  # Create a zip archive of the build artifacts TheDoctor0/zip-release@0.7.6
        with:
          files: build/windows/artifacts/*  # Specify files to include in the zip
      - name: Create Release  # Create a release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}  # Use commit SHA as the release tag
          draft: false  # Set to true for draft releases
          files: ${{ steps.zip.outputs.zip_file }}  # Upload the zip file as an asset
